name: Publish

on:
  # Disabled - not publishing to npm
  # release:
  #   types: [published]
  workflow_dispatch:
    inputs:
      version:
        type: string

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
          registry-url: https://registry.npmjs.org

      - run: yarn install --frozen-lockfile
        id: npm-install

      - run: npm version ${{ github.event.release.name || inputs.version }} --no-git-tag-version

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  notify-failure:
    needs: publish
    if: failure() && needs.publish.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v4.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.FSH_SLACK_BOT_TOKEN }}
          payload: |
            channel: "myevals-alerts"
            text: ":red_circle: Workflow *<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>* failed on `${{ github.ref_name }}`"
