name: Test on Windows

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - run: yarn install --frozen-lockfile
        id: npm-install

      - run: npm run lint
        if: steps.npm-install.conclusion == 'success' && (success() || failure())

      - run: npm run test
        if: steps.npm-install.conclusion == 'success' && (success() || failure())

      - run: npm run build
        if: steps.npm-install.conclusion == 'success' && (success() || failure())

  notify-failure:
    needs: deploy
    if: failure() && needs.deploy.result == 'failure' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v4.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.FSH_SLACK_BOT_TOKEN }}
          payload: |
            channel: "myevals-alerts"
            text: ":red_circle: Workflow *<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>* failed on `${{ github.ref_name }}`"
