name: Test & Deploy

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - run: yarn install --frozen-lockfile
        id: npm-install

      - run: npm run lint
        if: steps.npm-install.conclusion == 'success' && (success() || failure())

      - run: npm run test
        if: steps.npm-install.conclusion == 'success' && (success() || failure())

      - run: npm run build-host
        if: steps.npm-install.conclusion == 'success' && (success() || failure())

      - run: npm run build
        if: steps.npm-install.conclusion == 'success' && (success() || failure())

  deploy-host:
    permissions:
      contents: read
      pages: write
      id-token: write
    needs: test
    if: success() && github.ref_name == 'main'
    uses: ./.github/workflows/deploy-host.yml
    secrets: inherit

  notify-failure:
    needs: test
    if: failure() && needs.test.result == 'failure' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v4.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.FSH_SLACK_BOT_TOKEN }}
          payload: |
            channel: "myevals-alerts"
            text: ":red_circle: Workflow *<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>* failed on `${{ github.ref_name }}`"
